services:
  examsmpalfa:
    image: taqiussa/examsmpalfa:latest

    env_file:
      - .env

    networks:
      - web

    deploy:
      replicas: 2

      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=web"

        - "traefik.http.routers.smpalfaexam.rule=Host(`exam.smpalmusyaffa.sch.id`)"
        - "traefik.http.routers.smpalfaexam.entrypoints=websecure"
        - "traefik.http.routers.smpalfaexam.tls.certresolver=cloudflare"

        - "traefik.http.services.smpalfaexam.loadbalancer.server.port=3000"

networks:
  web:
    external: true