services:
  app:
    image: taqiussa/examelemenka:latest
    container_name: examelemenka
    restart: unless-stopped
    env_file:
      - .env
    pull_policy: ${PULL_POLICY:-always}
    networks:
      - web
    ports:
      - "8830:${APP_PORT}"

networks:
  web:
    external: true
