services:
  app:
    image: taqiussa/examsmkmifda:latest
    container_name: examsmkmifda
    restart: unless-stopped
    env_file:
      - .env
    pull_policy: ${PULL_POLICY:-always}
    networks:
      - proxy_network
    ports:
      - "8830:${APP_PORT}"

networks:
  proxy_network:
    external: true
