services:
  app:
    image: taqiussa/examelemenka:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: examelemenka
    restart: unless-stopped
    env_file:
      - .env
    pull_policy: ${PULL_POLICY:-if_not_present}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web
    ports:
      - "8830:3000"

networks:
  web:
    external: true
